# PLAYER:
PLAYER1_IMAGE = 'player.png'
POS_X = 20
POS_Y = 0
X_SIZE = 3
Y_SIZE = 10
HORI_VEL = 2
VERT_ACE = 0.2
MAX_VERT_VEL = 3
JUMP_HEIGHT = 4
MAX_AIRTIME = 6

# COLOR:
WHITE = (255, 255, 255)
BLUE = (146, 244, 255)
BLACK = (0, 0, 0)

# DISPLAY
WINDOW_SIZE = (600, 400)
SURFACE_SIZE = (300, 200)
TILE_SIZE = 16
GRASS_IMG = 'grass.png'
DIRT_IMG = 'dirt.png'
BRICK_IMG = 'brick.png'
LIFE_IMG = 'life.png'
PORTAL_IMG = 'portal.png'
LOST_IMG = 'lost.png'

LIFE_LOC = (0, 0)
LIFE_COUNT_LOC = (20, 0)

FONT_SIZE = 15
# MAP = 'map.txt'
FPS = 60

# SHOP
SHOP_W = 250
SHOP_H = 300
WINDOW_SIZE_X = 600
WINDOW_SIZE_Y = 400
SHOP_X = (WINDOW_SIZE_X - SHOP_W) / 2
SHOP_Y = (WINDOW_SIZE_Y - SHOP_H) / 2
ITEM_W = 100
ITEM_H = 100
TEXT_SIZE = 24
ITEM_ONE_NAME = "SPEED BOOST"
ITEM_TWO_NAME = "JUMP BOOST"
ITEM_THREE_NAME = "EXTRA LIFE"
ITEM1_IMAGE = 'Speed.png'
ITEM2_IMAGE = 'Jump.png'
ITEM3_IMAGE = 'ExtraLife.png'
TEXT_COLOR = [BLACK, BLACK, BLACK]

#level
MAX_LEVEL = 1

#ENEMY
ENEMY_IMAGE = 'monster.png'
ENEMY_SPEED = 1